### ISSUE TITLE
Dotted keys values go missing

### ISSUE THREAD

**Issue by nat-n** [sdispater/tomlkit#105]
Input:
```python
from tomlkit import parse
parse("""
namespace.key1 = "value1"
namespace.key2 = "value2"
""")
```

Expected output:
```python
{'namespace': {'key1': 'value1', 'key2': 'value2'}}
```

Actual output:
```python
{'namespace': {'key1': 'value1'}}
```

It seems subsequent additions to the subtable via a dotted key are lost.

---

UPDATE: After further investigation it looks like the bug must be in the TOMLDocument object rather than the parsing logic.

consider:
```python
>>> doc = parse("""
namespace.key1 = "value1"
namespace.key2 = "value2"
""")
>>> repr(doc)
"{'namespace': {'key1': 'value1'}}"
>>> dict(doc)
{'namespace': {'key1': 'value1'}}
>>> str(doc)
"{'namespace': {'key1': 'value1', 'key2': 'value2'}}"
```

**Comment by nat-n** [comment]
After further investigation it looks like the bug must be in the TOMLDocument type rather than the parsing logic.

consider:
```python
>>> result = parse("""
namespace.key1 = "value1"
namespace.key2 = "value2"
""")
>>> repr(result)
"{'namespace': {'key1': 'value1'}}"
>>> dict(result)
{'namespace': {'key1': 'value1'}}
>>> str(result)
"{'namespace': {'key1': 'value1', 'key2': 'value2'}}"
```

**Comment by zhkuo24** [comment]
suffer the same problem 🤣

**Comment by frostming** [comment]
I've created a fork of tomlkit v0.7.0 with the issue fixed, try it:

GitHub: https://github.com/frostming/atoml
PyPI: https://pypi.org/project/atoml
