### ISSUE TITLE
Indenting error in updating variables

### ISSUE THREAD

**Issue by yehonathanJacob** [sdispater/tomlkit#106]
While having this type of file:
```
[Key1]
      [key1.Key2]
      Value1 = 10
      Value2 = 30
```

I was trying to do update the `Value1`, doing so I use the code:
```
from tomlkit import dumps
from tomlkit.toml_file import TOMLFile

toml_doc = TOMLFile(path_to_file).read()
toml_doc["key1"]["key2"]["Value1"] = 20
dumps(toml_doc)
```

The resulting file was:
```
[Key1]
      [key1.Key2]
            Value1 = 20
      Value2 = 30
```
means, it added double indentation in the updated value

**Comment by frostming** [comment]
I've created a fork of tomlkit v0.7.0 with the issue fixed, try it:

GitHub: https://github.com/frostming/atoml
PyPI: https://pypi.org/project/atoml
