### ISSUE TITLE
changed quotation marks

### ISSUE THREAD

**Issue by jedie** [sdispater/tomlkit#112]
Poetry used tomlkit to replace the version number in pyproject.toml
We used single quotation marks but the version changes replace them with double quotation marks, e.g.:

![grafik](https://user-images.githubusercontent.com/71315/96270131-8808fc00-0fcb-11eb-8759-f408321338ed.png)

see also: https://github.com/python-poetry/poetry/issues/3226

**Comment by frostming** [comment]
This was fixed
