### ISSUE TITLE
Critical data loss

### ISSUE THREAD

**Issue by ofek** [sdispater/tomlkit#113]
Using latest `0.7.0`:

```pycon
>>> import tomlkit
>>>
>>> doc = tomlkit.parse("""
... [tool.poetry.foo]
... option = 'test'
...
... [tool.poetry.bar]
... option = 'test'
... """)
>>>
>>> doc
{'tool': {'poetry': {'foo': {'option': 'test'}, 'bar': {'option': 'test'}}}}
>>> doc['tool']
{'poetry': {'bar': {'option': 'test'}}}
>>> dict(doc['tool'])
{'poetry': {'bar': {'option': 'test'}}}
```

cc @frostming @sdispater

**Comment by eksortso** [comment]
Can you show us what `print(doc)` displays? Because there is a bug, but it doesn't cause critical data loss.

I tried your code using tomlkit `0.7.0` on Python `3.8.3`. Here's what I got.

```python
>>> print(doc)
{'tool': {'poetry': {'foo': {'option': 'test'}, 'bar': {'option': 'test'}}}}

>>> doc['tool']
{'poetry': {'bar': {'option': 'test'}}}


>>> doc['tool']['poetry']['foo']
{'option': 'test'}


>>> doc['tool']['poetry']['bar']
{'option': 'test'}
```

**Comment by ofek** [comment]
It shows the same as yours

**Comment by frostming** [comment]
`tomlkit`'s containers and tables inherits from built-in `dict` and has some but not all customized implementations of the magic methods. It often leads to issue where the native version of the method is called instead of the customized one.

**Comment by ofek** [comment]
Any update?

**Comment by frostming** [comment]
I've created a fork of tomlkit v0.7.0 with the issue fixed, try it:

GitHub: https://github.com/frostming/atoml
PyPI: https://pypi.org/project/atoml
