### ISSUE TITLE
Commas consumed as part of a comment?

### ISSUE THREAD

**Issue by njalerikson** [sdispater/tomlkit#13]
https://github.com/sdispater/tomlkit/blob/07442dcd5e9e9f44092d34f6f4a437316182c79f/tomlkit/parser.py#L342-L344

Why are commas being consumed as part of the whitespace before a comma?

```
import tomlkit
p = tomlkit.parser.Parser("hello = 'world'    ,  # this")
doc = p.parse()

doc
# {'hello': 'world'}
doc.as_string()
# "hello = 'world'    ,  # this"
doc["hello"]._trivia.indent
# ''
doc["hello"]._trivia.comment_ws
# '    ,  '
doc["hello"]._trivia.comment
# '# this'
doc["hello"]._trivia.trail
# ''
```

Simply removing the comma from the comment parsing also doesn't break any unittests.

**Comment by sdispater** [comment]
This is fixed in the latest release (`0.4.5`).
