### ISSUE TITLE
"TOMLDocument" has no attribute "get"

### ISSUE THREAD

**Issue by aahung** [sdispater/tomlkit#134]
Might be related to #130, the output of `tomlkit.loads()` does not have `get()` method.

> "TOMLDocument" has no attribute "get"

Version 0.7.2
Python 3.7.2
mypy: 0.790

According to the README:

> doc is a TOMLDocument instance that holds all the information
 about the TOML string.
 It behaves like a standard dictionary.

it should have all the methods of `dict`

**Comment by Secrus** [comment]
It seems that this issue has been resolved. Cannot reproduce, the `get` method works without any problem.
