### ISSUE TITLE
Newline in keys should be escaped

### ISSUE THREAD

**Issue by abadger** [sdispater/tomlkit#136]
Hi I was looking at the tomlkit behaviour with newlines in keys and found a bug:
``` python
>>> import tomlkit
>>> tomlkit.__version__
'0.5.11'
>>> print(tomlkit.dumps({'a\nb': 'a\nb'}))
"a
b" = "a\nb"
```

The toml spec says that the key, equal sign, and value must be on the same line (the value can span multiple lines if it is a multiline string but it must start on the same line as the other parts).  ( https://toml.io/en/v1.0.0#keyvalue-pair )

I asked for clarification of what should happen with newlines in key values on the toml lang github and the consensus was that the escaped form of a newline should be used instead of the actual newline: https://github.com/toml-lang/toml/issues/826

Thus the desired behaviour would be for tomlkit.dumps do this:

``` python
>>> print(tomlkit.dumps({'a\nb': 'a\nb'}))
"a\nb" = "a\nb"
```

**Comment by srinivasreddy** [comment]
Another relevant discussion. https://github.com/toml-lang/toml/issues/835
