### ISSUE TITLE
Inconsistency of items getter

### ISSUE THREAD

**Issue by T4rk1n** [sdispater/tomlkit#140]
To add an inline comment to a key, I usually do `section[key].comment(comment)`, where section is either a TOMLDocument or a table and comment a string.

In the case of a bool value, the returned object by `section[key]` is the bool value and not the item. So doing `section[key].comment` fails. I fixed by using `section.item(key)` but then when it's a table it doesn't have that method so it takes another condition.

https://github.com/T4rk1n/precept/issues/22

**Comment by frostming** [comment]
See https://github.com/sdispater/tomlkit/issues/119#issuecomment-955840942
