### ISSUE TITLE
Why doesn't order get preserved?

### ISSUE THREAD

**Issue by Mrodent** [sdispater/tomlkit#147]
I just tried adding the following:
- a comment
- a new line
- a comment
- a table, with 3 keys
- 2 free-standing keys

To my surprise, `dumps` then printed the free-standing keys after the initial comments and newline but before the table.

I assume this is perfectly intentional, and maybe follows a perfectly good rationale. But I'm just wondering whether `dumps` can be made to just show things in the order in which they have been added to the document?

Today (next day) I also find it pretty difficult to understand what's happened to comments: I'm talking about random comments, maybe added by some users, AFTER we have entered the part of the file where the tables have started: although such comments are not "ignored" during parsing, and certainly get printed out on `dumps`, I can't understand how to locate them in the document's `_body` structure. Maybe they're located somewhere else?

Some documentation, if only to guide us a bit when we try to understand the source code, might be nice.

**Comment by frostming** [comment]
> 2 free-standing keys

These can't appear after a table, otherwise they are parsed as the table keys, not free-standing keys
