### ISSUE TITLE
Add a doc site

### ISSUE THREAD

**Issue by frostming** [sdispater/tomlkit#161]

**Comment by frostming** [comment]
Hi, @sdispater , any chance adding the github integration of RTFD? The toolkit project on RTFD is owned by me now, I can add you as maintainer.

**Comment by remram44** [comment]
The link in the README is 404. What do you own @frostming?

**Comment by webknjaz** [comment]
> [readthedocs.org/projects/tomlkit/builds](https://readthedocs.org/projects/tomlkit/builds/) is failing for some reason

Here's the fix: https://github.com/sdispater/tomlkit/pull/251.
