### ISSUE TITLE
The `dumps()` function renders empty tables when a dict is the `data` argument

### ISSUE THREAD

**Issue by andreoliwa** [sdispater/tomlkit#166]
Hi there, and thanks for this project (and for Poetry)!

I'd like to render TOML from a `dict`, but currently `dumps()` is rendering empty tables.

Is there any solution or workaround for this?
I couldn't find any `loads()` or `dumps()` argument to ignore empty tables.

Here is an example:
```python
import tomlkit

print("# TOML rendered with an empty table:")
empty_table = {"tool": {"black": {"line-length": 120}}}
print(tomlkit.dumps(empty_table))

print("# TOML rendered with a double quoted key:")
double_quoted = {"tool.black": {"line-length": 120}}
print(tomlkit.dumps(double_quoted))

print(
    """# Desired TOML (no empty table and no double quoted key):
[tool.black]
line-length = 120
    """
)
```

**Comment by frostming** [comment]
You can't achieve this by primitive `dict` type. Instead, you should use `tomlkit`'s inner types:

```python
import tomlkit

doc = tomlkit.document()
tool_table = tomlkit.table()
tool_table._is_super_table = True  # super table won't be shown in the rendered result
# With the unreleased changes in the main branch, the above two lines can be replaced by:
# tool_table = tomlkit.table(is_super_table=True)
tool_table['black'] = {"line-length": 120}
doc["tool"] = tool_table
print(tomlkit.dumps(doc))
# will give you the desired result
```

**Comment by andreoliwa** [comment]
Thanks for the answer.
I will try doing as you said, but it doesn't solve my problem.

I have a dynamically generated `dict` that I'd like to convert to TOML.
I can't write custom code for every `dict` I'd like to dump as TOML.

**Comment by frostming** [comment]
That's it: use Python objects, get default styles; use `tomlkit` objects, get custom styles.
