### ISSUE TITLE
discriminant property of String(Item)

### ISSUE THREAD

**Issue by mxustin** [sdispater/tomlkit#198]
Hello,

please allow me to ask what is the purpose of the "discriminant" property for classes inherited from Item, for example, for the class String (line 1680 of the module items.py)?

**Comment by abravalheri** [comment]
Hi @mxustin, `discriminant` is just a runtime method to differentiate between the multiple classes of items. `Whitespace` has `discriminant == 0`, `Comment` has `discriminant == 1`, `Integer` has `discriminant == 2`, and so on...
