### ISSUE TITLE
Sorting an Array doesn't persist

### ISSUE THREAD

**Issue by davidgilbertson** [sdispater/tomlkit#233]
I'm trying to load a `pyproject.toml`, add a dependency, _sort_ the dependencies, then save again.

I'm trying this:
```py
pyproject = tomlkit.load(file)
deps = pyproject["project"]["dependencies"]
deps.append("a_new_package")
deps.sort() 
deps.multiline(True)

# save
```

But the `sort()` doesn't update the underlying `Array._value` so when it's saved the old order persists.

I've found that this works, but it's a tad verbose:
```py
pyproject = tomlkit.load(file)
deps = pyproject["project"]["dependencies"]
deps.append("a_new_package")
deps.sort()
array = tomlkit.array()
array.extend(deps)
array.multiline(True)
pyproject["project"]["dependencies"] = array

# save
```

Is there a better way?

**Comment by frostming** [comment]
And also `.reverse()`? But since `tomlkit` is a library to keep the styles and comments, how would you like to deal with the comments when elements are reordered?

**Comment by davidgilbertson** [comment]
Ooh, excellent question.  My answer is a bit self-referential :)

* I would guess that _if_ a user is calling sort on an array, then there is a low probability that they have inline comments. So you could sort by the string representation of each item (no special treatment of comments).
* Because sorting/reversing would create a mess of any array with comments, people with comments in arrays would not use sort, hence my suggestion that the people who _do_ use sort probably won't have comments to worry about.

You've made me think though, I need to add a check into my code that won't sort of there's any comment objects in that array.

**Comment by frostming** [comment]
Sorting and reversing are not valid use cases for a format-preserving TOML library, while you can always sorting on the Python native object get from `.unwrap()`
