### ISSUE TITLE
Python 3.11 str enum inconsistency

### ISSUE THREAD

**Issue by Tinche** [sdispater/tomlkit#237]
Hi folks,

not sure if you support 3.11 yet (or even plan on it), but I'm working to add support for it to cattrs. Since cattrs has a preconfigured converter for tomlkit, the test suite found a discrepancy.

```python
from enum import Enum

from tomlkit import dumps


class Test(str, Enum):
    A = "A"


print(dumps({Test.A: "a"}))
```

On 3.10:

```
A = "a"
```

On 3.11:

```
Test.A = "a"
```

**Comment by frostming** [comment]
The enum interface is a big inconsistency in the historic versions of Python. And Python 3.11 tries to address it.

Given this script:
```python
import tomlkit
from enum import Enum, IntEnum

class Foo(str, Enum):
    A = "A"

class IntFoo(IntEnum):
    ONE = 1

print("str(Enum):", str(Foo.A), "f-string:", f"{Foo.A}")
print("str(IntEnum):", str(IntFoo.ONE), "f-string:", f"{IntFoo.ONE}")
print("str key:", tomlkit.key(Foo.A).as_string())
print("str value:", tomlkit.item(Foo.A).as_string())
print("int value:", tomlkit.item(IntFoo.ONE).as_string())
```
Python 3.10 output, note that how f-string output differs from str().
```
str(Enum): Foo.A f-string: A
str(IntEnum): IntFoo.ONE f-string: 1
str key: A
str value: "A"
int value: IntFoo.ONE
```
Python 3.11 output:
```
str(Enum): Foo.A f-string: Foo.A
str(IntEnum): 1 f-string: 1
str key: Foo.A
str value: "A"
int value: 1
```

we wouldn't like to address this kind of mess in tomlkit, users should guarantee to pass primitive values as keys and values.
