### ISSUE TITLE
ValueError: Invalid type <class 'NoneType'>

### ISSUE THREAD

**Issue by amotl** [sdispater/tomlkit#240]
Dear @sdispater and @frostming,

thanks a stack for conceiving and maintaining this excellent library. We just wanted to let you know about an issue we just discovered when serializing `NoneType` values [1]. We are aware that TOML does not know about any kinds of NULL values (https://github.com/toml-lang/toml/issues/921).

This issue is merely a proposal to handle `NoneType` values gracefully by just ignoring them on serialization. The [`toml`](https://pypi.org/project/toml/) package does just that [2]. We have exercised the situation with all of `toml`, `tomlkit`, and `tomli-w` on behalf of a unit test at [3] and also reported the same issue to the author of `tomli-w` at https://github.com/hukkin/tomli-w/issues/39.

With kind regards,
Andreas.

[1] https://github.com/isarengineering/SecPi/issues/25
[2] https://github.com/isarengineering/SecPi/pull/27
[3] https://gist.github.com/amotl/4d8bc928d781a5d0fbc7f404396f8417

**Comment by amotl** [comment]
We also found that, when using the access pattern to directly serialize to a file,
```python
with open("testdrive.toml", "w") as config_file:
    tomlkit.dump(data, config_file)
```

`tomlkit` raises an exception, but still writes an empty file, when `data` contains any `NoneType` value.

**Comment by jcdrubay** [comment]
@amotl it would be nice instead of ignoring to keep as a comment instead of ignoring.

**Comment by amotl** [comment]
Dear Jean-Charles Drubay,

> It would be nice instead of ignoring to keep as a comment instead of ignoring.

Apologies that I don't understand your request. English is not my mother's tongue. Can I ask you to rephrase your statement?

With kind regards,
Andreas.

**Comment by jcdrubay** [comment]
Dear @amotl I have updated my previous reply to make it clearer. Sorry for this initial version that wasn't clear at all.

**Comment by frostming** [comment]
None type isn't supported by TOML spec and we are not going to do things beyond that. So no special handling, just as other parsers do. Closing it now
