### ISSUE TITLE
Array's commas

### ISSUE THREAD

**Issue by kenodegard** [sdispater/tomlkit#25]
In accordance with the grammar 

https://github.com/toml-lang/toml/blob/bb47759841ac368d86eb7a459bd7eea7162b9a80/toml.abnf#L188-L200

leading and duplicate commas are not allowed (trailing is allowed).

In other words the following cases should not be allowed (but currently are possible):

1. **No comma**:
    ```
    a = [ 12  34 ]
    ```

1. **Leading comma**:
    ```
    a = [ , 12 ]
    ```

1. **Duplicate comma**:
    ```
    a = [ 12 ,,,,,, 34 ]
    ```

**Comment by frostming** [comment]
This was fixed
