### ISSUE TITLE
Type checking with pyright/pylance shows `"__getitem__" method not defined on type "Item"`

### ISSUE THREAD

**Issue by patrickarmengol** [sdispater/tomlkit#254]
Previously raised in https://github.com/sdispater/tomlkit/issues/111; not sure why it was closed.

pyright/pylance type checking shows `"__getitem__" method not defined on type "Item"` for expression `doc["table"]["foo"]`, making b partially unknown. 

```python
from tomlkit import parse

content = """[table]
foo = "bar"  # String
"""

doc = parse(content)
doc["table"]["foo"] == "bar"
a = doc["table"]  # a is type Item | Container
b = a["foo"]  # b is type Unknown | Item | Container
```

**Comment by frostming** [comment]
You have to narrow down the type of `a` yourself. A value of a table can be any type.

**Comment by patrickarmengol** [comment]
> You have to narrow down the type of `a` yourself. A value of a table can be any type.

Thanks. I feel a bit silly looking back at this now. I was just following the example in the quickstart docs when I ran into this issue, but I see it's the same situation as something like a regular nested dictionary. 

```python
foo = {
    'a': {'b': 4, 'c': 5},
    'd': 6
}

bar = foo['a']
assert isinstance(bar, dict)
baz = bar['b']
```

Only problem is now I have to do some extra not-so-pretty imports just for type validation. 
```python
from tomlkit.container import Container
from tomlkit.items import Item
```

**Comment by deanqx** [comment]
I would suggest to use `TOMLDocument.value` to get `dict: [str, Any]` type. This won't show a pyright error.

```py
doc.value["table"]["foo"] == "bar"
```
