### ISSUE TITLE
Deep update changes layout

### ISSUE THREAD

**Issue by michaelaye** [sdispater/tomlkit#255]
I'm using this function to update my nested dic with several arrays, resetting anything that are non-URLs to empty strings:

```python
def deep_update(source, reset=''):
    d = source.copy()
    for key, value in source.items():
        if isinstance(value, Mapping) and value:
            returned = deep_update(source.get(key, {}))
            d[key] = returned
        elif not 'url' in key:
            d[key] = reset
    return d
```

Using a minimal example taken and slightly adapted from the Table section of the 1.0 TOML definition (https://github.com/toml-lang/toml/blob/1.0.0/toml.md#table):

```python
s ="""
[fruit]
apple.url = "https://my.apple.server"
apple.color = "red"
"""
dic = tomlkit.load(s)
```
This dic prints like this:

```python
{'fruit': {'apple': {'url': 'https://my.apple.server/', 'color': 'red'}}}
```
and nicely dumps back to text like so, exactly as given:

```python
print(tomlkit.dumps(dic))
```
```toml
[fruit]
apple.url = "https://my.apple.server/"
apple.color = "red"
```

However, when using above function to update the dic, resetting the value of `apple.color` to '': 

```python
newdic = deep_update(dic)
print(newdic)
```
it returns:
```python
{'fruit': {'apple': {'url': 'https://my.apple.server/', 'color': ''}}}
```
but the tomlkit.dump has now lost the original structure:

```python
print(toml.dumps(newdic))
```
```toml
[fruit]
[fruit.apple]
fruit.apple.url = "https://my.apple.server/"
fruit.apple.color = ""
```

Is this a tomlkit bug or is my `deep_update` function doing something wrong?
Note that I cannot simply loop over existing and known (key, value) pairs as the config file where I want to apply this is quite more complex.

 tomlkit version: 0.11.6 on Linux

**Comment by frostming** [comment]
Copy and reassign breaks the structure. Why not just deepcopy and update?

```python
def deep_update(source, reset=''):
    for key, value in source.items():
        if isinstance(value, Mapping) and value:
            deep_update(value, reset)
        elif not 'url' in key:
            source[key] = reset
    return source

newdic = deep_update(copy.deepcopy(dic))

```

**Comment by michaelaye** [comment]
Thank you for this tip, appreciate it!
