### ISSUE TITLE
Uncaught exception in parse

### ISSUE THREAD

**Issue by DavidKorczynski** [sdispater/tomlkit#276]
The following program raises an uncaught exception:

```python
import sys
import atheris
import tomlkit

def TestOneInput(data):
  fdp = atheris.FuzzedDataProvider(data)
  s1 = fdp.ConsumeUnicodeNoSurrogates(sys.maxsize)
  parser = tomlkit.parser.Parser(s1)
  try:
    parser.parse()
  except (
    tomlkit.exceptions.TOMLKitError,
    RecursionError
  ):
    pass

data = (b"\xff\x5b\x62\x5d\x8a\xa0\x5b\x62\x2e\x49\x2e\x62\x2e\x5a\x5d\x8a\x5b\x62\x2e\x49\x2e\x62\x5d")
TestOneInput(data)
```

Where the `atheris` module refers to https://pypi.org/project/atheris/

The program is a derivative of the fuzzer here https://github.com/google/oss-fuzz/blob/master/projects/tomlkit/fuzz_parser.py

The following program is a shortened version of above, without fuzzing-related logic:

```python
import tomlkit

raw_str = "\x5b\x62\x5d\x0a\x20\x5b\x62\x2e\x49\x2e\x62\x2e\x5a\x5d\x0a\x5b\x62\x2e\x49\x2e\x62\x5d"
parser = tomlkit.parser.Parser(raw_str)
try:
  parser.parse()
except (
  tomlkit.exceptions.TOMLKitError,
  RecursionError
):
  pass
```

This produces the stacktrace:
```
Traceback (most recent call last):
  File "./s_reproducer.py", line 20, in <module>
    parser.parse()
  File "/usr/local/lib/python3.8/site-packages/tomlkit/parser.py", line 158, in parse
    key, value = self._parse_table()
  File "/usr/local/lib/python3.8/site-packages/tomlkit/parser.py", line 1021, in _parse_table
    table.raw_append(key_next, table_next)
  File "/usr/local/lib/python3.8/site-packages/tomlkit/items.py", line 1616, in raw_append
    self._value.append(key, _item)
  File "/usr/local/lib/python3.8/site-packages/tomlkit/container.py", line 262, in append
    current.append(k, v)
  File "/usr/local/lib/python3.8/site-packages/tomlkit/items.py", line 1603, in append
    m = re.match("(?s)^([^ ]*)(.*)$", _item.trivia.indent)
AttributeError: 'OutOfOrderTableProxy' object has no attribute 'trivia'
```

This was found by way of OSS-Fuzz and the set up here: https://github.com/google/oss-fuzz/tree/master/projects/tomlkit If you find this issue helpful then it would be great to have maintainer emails in the [project.yaml](https://github.com/google/oss-fuzz/blob/master/projects/tomlkit/project.yaml) to receive notifications of bug reports, which contain all details similar to what I posted above -- namely they contain the stacktrace, crashing input and identification of the fuzzer.

**Comment by frostming** [comment]
This issue seems to be fixed on the master branch, closing it now.
