### ISSUE TITLE
KeyAlreadyPresent, if sections mix their order

### ISSUE THREAD

**Issue by vlcinsky** [sdispater/tomlkit#28]
Following test case
```python
import pytest
import tomlkit


@pytest.fixture
def toml_content():
    return """
[major]
name = "Charles Bownam"

[alien]
name = "et"

[major.clerk]
name = "John Barradell"
""".strip()


def test_parse(toml_content):
    doc = tomlkit.loads(toml_content)
    assert doc
```
raise: ```tomlkit.exceptions.KeyAlreadyPresent: Key "major" already exists.```

According to https://www.tomllint.com/ is the content valid TOML.

Affects https://github.com/sdispater/poetry/issues/563

**Comment by sdispater** [comment]
This is fixed in the latest releases.

**Comment by vlcinsky** [comment]
Great. I can confirm it works well now.
