### ISSUE TITLE
Missing types in the `append()` method of the `Table` class

### ISSUE THREAD

**Issue by joaopalmeiro** [sdispater/tomlkit#281]
Hi! 👋 

I think the types for the [`append()` method of the `Table` class](https://github.com/sdispater/tomlkit/blob/master/tomlkit/items.py#L1577) are missing, as this method is part of the "public API". If adding them makes sense and I can help, let me know. 

Thanks! 😄

**Comment by frostming** [comment]
Thanks, you can do it
