### ISSUE TITLE
I am switching to `rtoml`

### ISSUE THREAD

**Issue by caniko** [sdispater/tomlkit#293]
I switched to [`rtoml`](https://github.com/samuelcolvin/rtoml)  last month, it is both faster and supports `pathlib.Path` parsing from `.toml`.

Sharing my experience here for those that might follow my path in the future.

**Comment by frostming** [comment]
Not sure what you mean by "support":

```python
import rtoml
from pathlib import Path

a = {"path": Path("abc")}
rtoml.dumps(a)
```
```pytb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/fming/wkspace/github/test-pdm/.venv/lib/python3.11/site-packages/rtoml/__init__.py", line 49, in dumps
    return serialize(obj)
           ^^^^^^^^^^^^^^
_rtoml.TomlSerializationError: PosixPath('abc') (PosixPath) is not serializable to TOML
```
Also it doesn't preserve styles which is the most important feature of tomlkit.

**Comment by caniko** [comment]
There is a PR.

**Comment by frostming** [comment]
Yes but it's the only reason to use tomlkit, if you don't need it you just use other toml libs. Even I myself would do it like this. But don't throw complaints on the maintainers.

**Comment by caniko** [comment]
Not really complaining, just sharing my experience in case somebody else has the same issue.

`tomlkit` fills an important niche for those that want to be strict without ambiguity. It is just not for me.
