### ISSUE TITLE
Missing setup.py on releases?

### ISSUE THREAD

**Issue by luizribeiro** [sdispater/tomlkit#305]
While packaging `tomlkit` 0.11.8 for NixOS we noticed that starting on 0.11.7 the released packages no longer include `setup.py` (see full discussion on https://github.com/NixOS/nixpkgs/pull/245440).

While `setup.py` is no longer actually necessary, this creates a circular dependency to build `tomlkit` moving forward - as `tomlkit` itself would require `poetry` to be able to build `tomlkit`, while `poetry` itself depends on `tomlkit` to be built.

Was the removal of `setup.py` intended?

**Comment by luizribeiro** [comment]
Ah, it seems like this happened because of https://github.com/python-poetry/poetry-core/pull/318

I guess we could explicitly set `tool.poetry.build.generate-setup-file` here so we can still build `tomlkit` without `poetry`?

I'm going to put up a PR for that.

**Comment by frostming** [comment]
> this creates a circular dependency to build `tomlkit` moving forward - as `tomlkit` itself would require `poetry` to be able to build `tomlkit`, while `poetry` itself depends on `tomlkit` to be built.

This is not true, `tomlkit` only requires `poetry-core` to build and the latter has zero-dependency, it doesn't vendor tomlkit either. You may need to investigate carefully to find out the real cause.

**Comment by luizribeiro** [comment]
Thank you for the clarification, @frostming!

It looks like nixpkgs has the wrong dependencies for `poetry-core` indeed.

Feel free to close this issue (and the PR) if you feel like there shouldn’t be any changes upstream.
