### ISSUE TITLE
[DOC] Missing `TOMLDocument.unwrap` et al in API Reference

### ISSUE THREAD

**Issue by n-takumasa** [sdispater/tomlkit#315]
The [API Reference](https://tomlkit.readthedocs.io/en/latest/api/) is generated based on docstrings, so some public APIs are not visible in the documentation.

For example: [TOMLDocument.unwrap (Container.unwrap)](https://github.com/sdispater/tomlkit/blob/cfc99766fc9fc4f05c57c45487bea319e96e1eba/tomlkit/container.py#L46)

**Comment by frostming** [comment]
Contribution welcome
