### ISSUE TITLE
Version 0.12.2 tag seems to have been moved

### ISSUE THREAD

**Issue by nanonyme** [sdispater/tomlkit#322]
We seem to have the tag 0.12.2 with ref a1a8d3721dc175faf62b891d9e1e68aaae4052ab whereas this repo now has the tag at b83b7dbb362dc189b07096a6a4ed494f57488251. It is not at all normal git usage to move tags as any changes with tags *do not propagate* to other repos. Was this tag accidentally moved?

**Comment by nanonyme** [comment]
That is, while branches are mutable anchors, tags in git are expected to be globally (across repository network) immutable anchors for commits.

**Comment by nanonyme** [comment]
Appears this was done by @frostming in https://github.com/sdispater/tomlkit/releases/tag/0.12.2. This is not something that can be done with git as it's a distributed version control system. Please make a new version instead.

**Comment by frostming** [comment]
I have released a new version, and I don't know how to handle the old version. Should I just leave it as it is?

**Comment by nanonyme** [comment]
Yes, thanks
