### ISSUE TITLE
Inheriting from dict

### ISSUE THREAD

**Issue by energizah** [sdispater/tomlkit#36]
Hi, I'm getting started with tomlkit. I noticed that `Container` inherits from dict, which means its behavior may be difficult to predict in different environments. 

In particular, quoting from PyPy's docs about [subclassing builtin types](https://pypy.readthedocs.io/en/latest/cpython_differences.html#subclasses-of-built-in-types):

> Officially, CPython has no rule at all for when exactly overridden method of subclasses of built-in types get implicitly called or not. As an approximation, these methods are never called by other built-in methods of the same object. For example, an overridden __getitem__() in a subclass of dict will not be called by e.g. the built-in get() method.

As far as I can tell, though, most of the methods are already explicitly implemented in `Container`, so this unpredictability could be eliminated by subclassing `collections.abc.MutableMapping` instead.

**Comment by frostming** [comment]
Fixed
