### ISSUE TITLE
Include unittests in pypi sdist archive

### ISSUE THREAD

**Issue by scarabeusiv** [sdispater/tomlkit#39]
Could you please add MANIFEST.in and include tests in the sdist archive? In distributions we execute tests on the packages to ensure some sanity checking as othewise python packages are just copying files and we wouldn't know if something broke them.

**Comment by nedbat** [comment]
Hi, I'm not part of the tomlkit project, but I noticed this issue and am curious about it.  What distributions do you mean, and how do you know how to execute the tests in the sdist?

**Comment by scarabeusiv** [comment]
In this case if the tests are part of the source archive we would simply execute the tests using pytest.
But this issue seems to be fixed itself as the tests are now present (see the %check part)

https://build.opensuse.org/package/view_file/devel:languages:python/python-tomlkit/python-tomlkit.spec?expand=1
