### ISSUE TITLE
Document gets messed up when subtable is defined after another table

### ISSUE THREAD

**Issue by frostming** [sdispater/tomlkit#42]
```python
>>> import tomlkit
>>> contents = """\
... [students]
... tommy = 87
... mary = 66
... 
... [subjects]
... maths = "maths"
... english = "english"
... 
... [students.bob]
... score = 91
... """
>>> d = tomlkit.loads(contents)
>>> d.get('students')
{'bob': {'score': 91}}
>>> d
{'students': {'tommy': 87, 'mary': 66, 'bob': {'score': 91}},
 'subjects': {'maths': 'maths', 'english': 'english'},
 'students': {'tommy': 87, 'mary': 66, 'bob': {'score': 91}}}
```

We defined `[students.bob]` section after `[subjects]`, while this format is supported by TOML spec.

**Comment by rambo** [comment]
Just letting know that I ran into this as well:

https://gitlab.com/advian-oss/python-datastreamservicelib/-/blob/master/tests/test_confiparser.py#L20

my first symptom was the source plugin complaining about missing arguments to init, it tooks a bit of figuring out that the dict cast (or `.copy()`) is what's going to mess things up.

**Comment by frostming** [comment]
This was fixed
