### ISSUE TITLE
Multiline dump?

### ISSUE THREAD

**Issue by simplesteph** [sdispater/tomlkit#44]
If a string contains `\n`, is it possible to dump as multiline? e.g
```
foo = """
my 
string
"""
```

**Comment by funkyfuture** [comment]
before i *might* start working on an implementation, i'd like to have some feedback on the design. my approach would be similar to the newline feature:

```python
document.add(ml("""
Hello world,

feelin' steamy?
"""))
```

`ml` has a very short hamming distance to `nl` though, and is easy to mistype these two. but maybe this doesn't need to be discussed when `newline` can be introduced as alias for `nl` and `multiline` would be one for `ml`.

**Comment by funkyfuture** [comment]
in case someone wants to put it into its application:

```python
def multiline_string(value: str) -> tomlkit.items.String:
    return tomlkit.items.String(tomlkit.items.StringType.MLB, value, value, tomlkit.items.Trivia())
```

**Comment by vvasuki** [comment]
Would be a very useful feature.
