### ISSUE TITLE
Document how to create a table without the supers

### ISSUE THREAD

**Issue by epage** [sdispater/tomlkit#47]
I'm trying to create
```toml
[a.b.c]
d = 10
```
but I get
```toml
[a]
[a.b]
[a.b.c]
d = 10
```

Looking around, somethings I see that might be useful
- `tomlkit.items.Table(..., is_super_table)` but am unclear where I apply it and what problems I need to avoid vs what is enforced for me
- `tomlkit.items.Key` supports a type and dotted but it is unclear what should be done.
  - Even if I pass `dotted=True`, it looks like it'll still get a `Basic` type and be quoted.  So I need to specify both `Bare` and `dotted`?

**Comment by sloria** [comment]
I was able to do this by loading a document with the top-level tables.

```python

In [1]: import tomlkit

In [2]: doc = tomlkit.loads("[a.b.c]")

In [3]: doc['a']['b']['c']['d'] = 10

In [4]: print(tomlkit.dumps(doc))
[a.b.c]
d = 10
```

Poetry does something similar with loading template strings: https://github.com/python-poetry/poetry/blob/ed4434253762f943255af20e98098b19a65ca1a6/poetry/layouts/layout.py#L16
