### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by suikastar** [sdispater/tomlkit#59]
#### code
```python
from tomlkit import dumps, parse

doc = parse("""[target.x86_64-pc-windows-gnu]
linker = "D:/msys64/mingw64/bin/gcc.exe"
ar = "D:/msys64/mingw64/bin/ar.exe"
""")
doc.remove("target.x86_64-pc-windows-gnu")
print(dumps(doc))
```

#### remove failure
`tomlkit.exceptions.NonExistentKey: 'Key ""target.x86_64-pc-windows-gnu"" does not exist.'`

**Comment by sdispater** [comment]
`[target.x86_64-pc-windows-gnu]` is a table which is accessible like this: `doc["target"]["x86_64-pc-windows-gnu"]`.

If you want the name of your table to be `target.x86_64-pc-windows-gnu` then you will have to quote it: `["target.x86_64-pc-windows-gnu"]`
