### ISSUE TITLE
tomlkit.items.Array missing implementation of insert, extend, remove etc

### ISSUE THREAD

**Issue by Garagoth** [sdispater/tomlkit#61]
`tomlkit.items.Array` inherits a `list`, but overrides only `append` method.
Remaining methods execute but do nothing, so it is not possible to remove elements from list or insert new one in specific place, making editing files very problematic.

**Comment by kaptajnen** [comment]
Came across this issue as well. tomlkit.items.Array does implement `__delitem__` so you can delete an item with `del doc["array"][doc["array"].index(s)]` to get functionality similar to `list.remove(s)`. It's not pretty though.

**Comment by Mrodent** [comment]
Ooh, nasty! Failing silently = not good!

Obvious thing to use `insert` is a list comprehension: 

```
mru = [x for x in self.parsed_toml_doc['mru_files']]
mru.insert(0, thing)

```
and then reset 

`self.parsed_toml_doc['mru_files'] = mru`

**Comment by frostming** [comment]
This was fixed
