### ISSUE TITLE
[Maintainance] Willing to maintain tomlkit

### ISSUE THREAD

**Issue by frostming** [sdispater/tomlkit#62]
I sent an email to Sebastien a month ago but got no reply. Here I request again to be a maintainer of tomlkit.

I am also a maintainer of Pipenv which depends on tomlkit heavily, but due to some bugs(#56 ), things get broken. This project hasn't seen any new activities for the last months, so I volunteer to pick it up. PyPI access would be even greater.

I appreciate for your great work in so many wonderful projects @sdispater

**Comment by frostming** [comment]
I am currently maintaining a fork: https://github.com/frostming/atoml that includes a lot of fixes, some of which are still around in tomlkit: #145, #146, #148

@sdispater ping again, may I have the access to maintain this project? I will merge the changes made in atoml back. However, the codebase of atoml is python 3.6+ so I would like to know if you are okay with this chanage.

**Comment by sdispater** [comment]
Hi @frostming, thanks for reaching out again 🙂 And I'm glad you did.

Yes, ì can make you a co-maintainer of the project. `tomlkit` needs some love that I don't have time to give at the moment.

And I have no issue making it compatible with 3.6+ (and even 3.7+) only. We just need to make a `0.7` branch in case we need to fix critical/security issues.
