### ISSUE TITLE
Use super() without arguments to allow monkey-patching 

### ISSUE THREAD

**Issue by acetylen** [sdispater/tomlkit#75]
If I want to overload functionality for use in multiple places in my application, I would usually monkey-patch it in:

```python
import tomlkit

class MyContainer(tomlkit.container.Container):
    """Transforms requested data in some way before returning it"""
    def __getitem__(self, key):
        item = super().__getitem__(key)
        return some_transform(item)

tomlkit.container.Container = MyContainer
```

However, since tomlkit uses `super(Type, self)` for superclass access everywhere rather than just `super()`, `__getitem__` fails with `TypeError: super(type, obj): obj must be an instance or subtype of type`.

[Further reading](https://rhettinger.wordpress.com/2011/05/26/super-considered-super/)

**Comment by frostming** [comment]
Fixed
