### ISSUE TITLE
Not having an empty newline at the end makes the file corrupt itself after dumping

### ISSUE THREAD

**Issue by xNinjaKittyx** [sdispater/tomlkit#97]
Gist:https://gist.github.com/xNinjaKittyx/1680e3159026089986df98a62eec02cc

Initially thought it was a poetry bug, but I went ahead and checked the parser using this

```Python
import tomlkit
print(tomlkit.dumps(tomlkit.loads(open('pyproject.toml').read())))
```

with the gist saved as pyproject.toml in the local folder. 
It will end up corrupting itself (as shown in the comment of the gist).

I have tested using pypoetry's version 0.5.11 as well as 0.6.0 from pypi

**Comment by frostming** [comment]
I've created a fork of tomlkit v0.7.0 with the issue fixed, try it:

GitHub: https://github.com/frostming/atoml
PyPI: https://pypi.org/project/atoml
